[package]
name = "linalg"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
path = "tests/benchmarks.rs"

[dependencies]
num = "0.4.3"
num-traits = "0.2.19"
rand = "0.8.5"
